Repository yujeong-shin/OrTopia, pull requests merged in 2024-04, with the labels that each got.

#17 [feat] Item server ResponseEtity 와 Error 공통화 작업
  item/src/main/java/com/example/ordering_lecture/common/ErrorCode.java
  item/src/main/java/com/example/ordering_lecture/common/ItemExceptionHandler.java
  item/src/main/java/com/example/ordering_lecture/common/OrTopiaException.java
  item/src/main/java/com/example/ordering_lecture/common/OrTopiaResponse.java
  item/src/main/java/com/example/ordering_lecture/item/controller/ItemController.java
  item/src/main/java/com/example/ordering_lecture/item/dto/ItemRequestDto.java
  item/src/main/java/com/example/ordering_lecture/item/service/ItemService.java
  item/src/main/java/com/example/ordering_lecture/review/controller/ReviewController.java
  item/src/main/java/com/example/ordering_lecture/review/dto/ReviewRequestDto.java
  item/src/main/java/com/example/ordering_lecture/review/dto/ReviewResponseDto.java
  item/src/main/java/com/example/ordering_lecture/review/dto/ReviewUpdateDto.java
  item/src/main/java/com/example/ordering_lecture/review/entity/Review.java
  item/src/main/java/com/example/ordering_lecture/review/repository/ReviewRepository.java
  item/src/main/java/com/example/ordering_lecture/review/service/ReviewService.java
Labels: 🍀코드리뷰

#19 [refactor ] item entity의 sellerEmail을 SellerId로 변경.
  item/src/main/java/com/example/ordering_lecture/item/dto/ItemRequestDto.java
  item/src/main/java/com/example/ordering_lecture/item/dto/ItemResponseDto.java
  item/src/main/java/com/example/ordering_lecture/item/dto/ItemUpdateDto.java
  item/src/main/java/com/example/ordering_lecture/item/entity/Item.java
  item/src/main/java/com/example/ordering_lecture/item/repository/ItemRepository.java
  item/src/main/java/com/example/ordering_lecture/item/service/ItemService.java
Labels: 🔼백엔드-개발

#18 [feat] vue3, vuetify3 세팅 및 Home, Header, Footer, Notice 초기 화면 구현
  ordering-frontend/front-end/.gitignore
  ordering-frontend/front-end/README.md
  ordering-frontend/front-end/babel.config.js
  ordering-frontend/front-end/jsconfig.json
  ordering-frontend/front-end/package-lock.json
  ordering-frontend/front-end/package.json
  ordering-frontend/front-end/public/favicon.ico
  ordering-frontend/front-end/public/index.html
  ordering-frontend/front-end/src/App.vue
  ordering-frontend/front-end/src/assets/logo.png
  ordering-frontend/front-end/src/assets/logo.svg
  ordering-frontend/front-end/src/assets/logo.webp
  ordering-frontend/front-end/src/components/FooterComponent.vue
  ordering-frontend/front-end/src/components/HeaderComponent.vue
  ordering-frontend/front-end/src/components/HomeComponent.vue
  ordering-frontend/front-end/src/components/NoticeComponent.vue
  ordering-frontend/front-end/src/main.js
  ordering-frontend/front-end/src/plugins/vuetify.js
  ordering-frontend/front-end/src/plugins/webfontloader.js
  ordering-frontend/front-end/src/router/index.js
  ordering-frontend/front-end/vue.config.js
  ordering-frontend/package-lock.json
  ordering-frontend/src/App.vue
  ordering-frontend/src/assets/logo.svg
  ordering-frontend/src/components/FooterComponent.vue
  ordering-frontend/src/components/HeaderComponent.vue
  ordering-frontend/src/components/HomeComponent.vue
  ordering-frontend/src/main.js
  ordering-frontend/src/plugins/vuetify.js
  ordering-frontend/vue.config.js
Labels: ⏫프론트-개발

#15 [feat] Address CRUD , Coupon CRUD 구현
  .idea/compiler.xml
  member/src/main/java/com/example/ordering_lecture/MemberApplication.java
  member/src/main/java/com/example/ordering_lecture/address/cotroller/AddressController.java
  member/src/main/java/com/example/ordering_lecture/address/domain/Address.java
  member/src/main/java/com/example/ordering_lecture/address/dto/AddressRequestDto.java
  member/src/main/java/com/example/ordering_lecture/address/dto/AddressResponseDto.java
  member/src/main/java/com/example/ordering_lecture/address/dto/AddressUpdateDto.java
  member/src/main/java/com/example/ordering_lecture/address/repository/AddressRepository.java
  member/src/main/java/com/example/ordering_lecture/address/service/AddressService.java
  member/src/main/java/com/example/ordering_lecture/coupon/controller/CouponController.java
  member/src/main/java/com/example/ordering_lecture/coupon/domain/Coupon.java
  member/src/main/java/com/example/ordering_lecture/coupon/dto/CouponRequestDto.java
  member/src/main/java/com/example/ordering_lecture/coupon/dto/CouponResponseDto.java
  member/src/main/java/com/example/ordering_lecture/coupon/repository/CouponRepository.java
  member/src/main/java/com/example/ordering_lecture/coupon/service/CouponService.java
  member/src/main/java/com/example/ordering_lecture/coupondetail/controller/CouponDetailController.java
  member/src/main/java/com/example/ordering_lecture/coupondetail/domain/CouponDetail.java
  member/src/main/java/com/example/ordering_lecture/coupondetail/dto/CouponDetailRequestDto.java
  member/src/main/java/com/example/ordering_lecture/coupondetail/dto/CouponDetailResponseDto.java
  member/src/main/java/com/example/ordering_lecture/coupondetail/dto/CouponDetailUpdateDto.java
  member/src/main/java/com/example/ordering_lecture/coupondetail/repository/CouponDetailRepository.java
  member/src/main/java/com/example/ordering_lecture/coupondetail/service/CouponDetailService.java
  member/src/main/java/com/example/ordering_lecture/member/domain/Address.java
  member/src/main/java/com/example/ordering_lecture/member/domain/Member.java
  member/src/main/java/com/example/ordering_lecture/membercoupon/cotroller/MemberCouponCotroller.java
  member/src/main/java/com/example/ordering_lecture/membercoupon/domain/MemberCoupon.java
  member/src/main/java/com/example/ordering_lecture/membercoupon/dto/MemberCouponRequestDto.java
  member/src/main/java/com/example/ordering_lecture/membercoupon/dto/MemberCouponResponseDto.java
  member/src/main/java/com/example/ordering_lecture/membercoupon/repository/MemberCouponRepository.java
  member/src/main/java/com/example/ordering_lecture/membercoupon/service/MemberCouponService.java
  notice/src/main/java/com/example/ordering_lecture/notice/controller/NoticeController.java
Labels: 🍀코드리뷰, 🔼백엔드-개발

#20 [feat] 추천 알고리즘에 필요한 데이터 추출
  .idea/modules.xml
  item/build.gradle
  item/src/main/java/com/example/ordering_lecture/item/controller/ItemController.java
  item/src/main/java/com/example/ordering_lecture/item/dto/ItemUpdateDto.java
  item/src/main/java/com/example/ordering_lecture/item/entity/Item.java
  item/src/main/java/com/example/ordering_lecture/item/repository/ItemRepository.java
  item/src/main/java/com/example/ordering_lecture/recommendation/controller/CsvExportController.java
  item/src/main/java/com/example/ordering_lecture/recommendation/dto/ReviewData.java
  item/src/main/java/com/example/ordering_lecture/recommendation/service/CsvExportService.java
  member/src/main/java/com/example/ordering_lecture/member/repository/BannedSellerRepository.java
  member/src/main/java/com/example/ordering_lecture/member/service/SellerService.java
Labels: 🍀코드리뷰, 🔼백엔드-개발

#22 [feat] member server commonentity 작업
  member/src/main/java/com/example/ordering_lecture/common/ErrorCode.java
  member/src/main/java/com/example/ordering_lecture/common/ErrorResponseDto.java
  member/src/main/java/com/example/ordering_lecture/common/InitialDataLoader.java
  member/src/main/java/com/example/ordering_lecture/common/MemberExceptionHandler.java
  member/src/main/java/com/example/ordering_lecture/common/OrTopiaException.java
  member/src/main/java/com/example/ordering_lecture/common/OrTopiaResponse.java
  member/src/main/java/com/example/ordering_lecture/member/controller/MemberController.java
  member/src/main/java/com/example/ordering_lecture/member/controller/SellerController.java
  member/src/main/java/com/example/ordering_lecture/member/dto/Buyer/MemberLikeSellerRequestDto.java
  member/src/main/java/com/example/ordering_lecture/member/dto/Buyer/MemberRequestDto.java
  member/src/main/java/com/example/ordering_lecture/member/dto/Seller/BannedSellerRequestDto.java
  member/src/main/java/com/example/ordering_lecture/member/dto/Seller/SellerRequestDto.java
  member/src/main/java/com/example/ordering_lecture/member/service/MemberService.java
  member/src/main/java/com/example/ordering_lecture/member/service/SellerService.java
Labels: 🍀코드리뷰, 🔼백엔드-개발

#24 feat: (front)item detail page
  ordering-frontend/front-end/package-lock.json
  ordering-frontend/front-end/src/App.vue
  ordering-frontend/front-end/src/components/HeaderComponent.vue
  ordering-frontend/front-end/src/components/HomeComponent.vue
  ordering-frontend/front-end/src/components/ItemComponent.vue
  ordering-frontend/front-end/src/components/MypageComponent.vue
  ordering-frontend/front-end/src/components/NoticeComponent.vue
  ordering-frontend/front-end/src/router/index.js
Labels: ⏫프론트-개발, 🍀코드리뷰

#29 [feat] Recommendation algorithm 구현
  .gitignore
  recommendation/.gitignore
  recommendation/build.gradle
  recommendation/gradle/wrapper/gradle-wrapper.jar
  recommendation/gradle/wrapper/gradle-wrapper.properties
  recommendation/gradlew
  recommendation/gradlew.bat
  recommendation/settings.gradle
  recommendation/src/main/java/com/example/ordering_lecture/RecommendApplication.java
  recommendation/src/main/java/com/example/ordering_lecture/common/ErrorCode.java
  recommendation/src/main/java/com/example/ordering_lecture/common/ItemExceptionHandler.java
  recommendation/src/main/java/com/example/ordering_lecture/common/OrTopiaException.java
  recommendation/src/main/java/com/example/ordering_lecture/common/OrTopiaResponse.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/Recommendation.csv
  recommendation/src/main/java/com/example/ordering_lecture/recommend/controller/RecommendationController.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/dto/ReviewData.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/entity/Category.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/entity/Item.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/service/RecommendationService.java
  recommendation/src/main/java/com/example/ordering_lecture/review/entity/Review.java
  recommendation/src/main/java/com/example/ordering_lecture/review/repository/ReviewRepository.java
  recommendation/src/main/resources/application.yml
  recommendation/src/test/java/com/example/ordering_lecture/OrderingLectureApplicationTests.java
Labels: 🍀코드리뷰, 🔼백엔드-개발

#39 [feat] Redis에 아이템 추천 리스트 저장
  .idea/compiler.xml
  .idea/misc.xml
  item/build.gradle
  item/src/main/java/com/example/ordering_lecture/recommendation/controller/CsvExportController.java
  item/src/main/java/com/example/ordering_lecture/recommendation/dto/ReviewData.java
  item/src/main/java/com/example/ordering_lecture/recommendation/service/CsvExportService.java
  recommendation/build.gradle
  recommendation/src/main/java/com/example/ordering_lecture/common/ErrorCode.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/Recommendation.csv
  recommendation/src/main/java/com/example/ordering_lecture/recommend/controller/RecommendationController.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/dto/RecommendationRedisData.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/dto/ReviewData.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/entity/Item.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/service/RecommendationService.java
  recommendation/src/main/java/com/example/ordering_lecture/redis/RedisConfig.java
  recommendation/src/main/java/com/example/ordering_lecture/redis/RedisService.java
  recommendation/src/main/java/com/example/ordering_lecture/review/entity/Review.java
  recommendation/src/main/java/com/example/ordering_lecture/review/repository/ReviewRepository.java
  recommendation/src/main/resources/application.yml
Labels: 🔼백엔드-개발

#52 merge fix
  .idea/compiler.xml
  .idea/misc.xml
  item/build.gradle
  item/src/main/java/com/example/ordering_lecture/item/controller/ItemController.java
  item/src/main/java/com/example/ordering_lecture/item/repository/ItemRepository.java
  item/src/main/java/com/example/ordering_lecture/item/service/ItemService.java
  item/src/main/java/com/example/ordering_lecture/recommendation/controller/CsvExportController.java
  item/src/main/java/com/example/ordering_lecture/recommendation/dto/ReviewData.java
  item/src/main/java/com/example/ordering_lecture/recommendation/service/CsvExportService.java
  recommendation/build.gradle
  recommendation/src/main/java/com/example/ordering_lecture/RecommendApplication.java
  recommendation/src/main/java/com/example/ordering_lecture/common/ErrorCode.java
  recommendation/src/main/java/com/example/ordering_lecture/feign/FeignClient.java
  recommendation/src/main/java/com/example/ordering_lecture/feign/MyFeignClientConfig.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/Recommendation.csv
  recommendation/src/main/java/com/example/ordering_lecture/recommend/controller/RecommendationController.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/dto/RecommendationRedisData.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/dto/ReviewData.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/entity/Category.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/entity/Item.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/service/RecommendationScheduler.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/service/RecommendationService.java
  recommendation/src/main/java/com/example/ordering_lecture/recommend/token/JwtTokenProvider.java
  recommendation/src/main/java/com/example/ordering_lecture/redis/RedisConfig.java
  recommendation/src/main/java/com/example/ordering_lecture/redis/RedisService.java
  recommendation/src/main/java/com/example/ordering_lecture/review/entity/Review.java
  recommendation/src/main/java/com/example/ordering_lecture/review/repository/ReviewRepository.java
  recommendation/src/main/resources/application.yml
Labels: 🔼백엔드-개발

#58 Seller 및 여러부분 페이지 구현했습니다. 포트번호를 고정시켰습니다.
  ordering-frontend/front-end/package-lock.json
  ordering-frontend/front-end/package.json
  ordering-frontend/front-end/src/components/HeaderComponent.vue
  ordering-frontend/front-end/src/components/ItemComponent.vue
  ordering-frontend/front-end/src/components/ItemCreateComponent.vue
  ordering-frontend/front-end/src/components/ItemListModal.vue
  ordering-frontend/front-end/src/components/MypageComponent.vue
  ordering-frontend/front-end/src/components/SellerCreateComponent.vue
  ordering-frontend/front-end/src/router/index.js
Labels: ⏫프론트-개발

#57 [feat]판매부분 및 쓸모없는 부분 정리 했습니다. 추가적으로 수정된 부분이 다수 있습니다.
  .idea/compiler.xml
  item/src/main/java/com/example/ordering_lecture/item/controller/ItemController.java
  item/src/main/java/com/example/ordering_lecture/item/dto/ItemResponseDto.java
  item/src/main/java/com/example/ordering_lecture/item/service/ItemService.java
  item/src/main/resources/application.yml
  member/src/main/java/com/example/ordering_lecture/common/InitialDataLoader.java
  member/src/main/java/com/example/ordering_lecture/member/controller/SellerController.java
  member/src/main/java/com/example/ordering_lecture/member/service/SellerService.java
  member/src/main/java/com/example/ordering_lecture/securities/JwtTokenProvider.java
Labels: 🔼백엔드-개발

#65 [feat] 아이디 찾기 비밀번호 찾기
  gateway/src/main/java/com/example/ordering_lecture/securities/JwtGlobalFilter.java
  member/build.gradle
  member/src/main/java/com/example/ordering_lecture/email/MailController.java
  member/src/main/java/com/example/ordering_lecture/email/MailService.java
  member/src/main/java/com/example/ordering_lecture/email/PasswordResetToken.java
  member/src/main/java/com/example/ordering_lecture/email/PasswordResetTokenRepository.java
  member/src/main/java/com/example/ordering_lecture/member/domain/Member.java
  member/src/main/java/com/example/ordering_lecture/member/dto/Buyer/MemberNewpasswordRequestDto.java
  member/src/main/java/com/example/ordering_lecture/member/service/MemberService.java
  notice/build.gradle
Labels: 🔼백엔드-개발

#66 [feat] 아이디 비밀번호 찾기 구현했습니다.
  ordering-frontend/front-end/src/components/FindIdModal.vue
  ordering-frontend/front-end/src/components/LoginComponent.vue
  ordering-frontend/front-end/src/components/NewPasswordComponent.vue
  ordering-frontend/front-end/src/components/ResetPasswordModal.vue
  ordering-frontend/front-end/src/router/index.js
Labels: ⏫프론트-개발

#78 [feat] statue 컬럼 이동으로 인한 그래프 코드 수정
  item/src/main/java/com/example/ordering_lecture/item/controller/ItemController.java
  order/src/main/java/com/example/ordering_lecture/order/OrderingController.java
  order/src/main/java/com/example/ordering_lecture/order/repository/OrderRepository.java
  order/src/main/java/com/example/ordering_lecture/order/service/OrderingService.java
  order/src/main/java/com/example/ordering_lecture/orderdetail/controller/MemberServiceClient.java
  order/src/main/java/com/example/ordering_lecture/orderdetail/dto/BuyerGraphCountData.java
  order/src/main/java/com/example/ordering_lecture/orderdetail/dto/BuyerGraphPriceData.java
  order/src/main/java/com/example/ordering_lecture/orderdetail/dto/SellerGraphCountData.java
  order/src/main/java/com/example/ordering_lecture/orderdetail/dto/SellerGraphPriceData.java
  order/src/main/java/com/example/ordering_lecture/orderdetail/repository/OrderDetailRepository.java
  order/src/main/java/com/example/ordering_lecture/payment/controller/ItemServiceClient.java
Labels: 🔼백엔드-개발

#79 [feat] 아이템별 판매 금액 그래프 시각화
  order/src/main/java/com/example/ordering_lecture/order/OrderingController.java
  order/src/main/java/com/example/ordering_lecture/order/service/OrderingService.java
  order/src/main/java/com/example/ordering_lecture/orderdetail/OrderDetailController.java
  order/src/main/java/com/example/ordering_lecture/orderdetail/dto/SellerGraphItemPriceData.java
  order/src/main/java/com/example/ordering_lecture/orderdetail/repository/OrderDetailRepository.java
  order/src/main/java/com/example/ordering_lecture/orderdetail/service/OrderDetailService.java
Labels: 🔼백엔드-개발
